name: Build (Windows / MSYS2)

on:
  push:
    paths:
      - 'src/*'
      - 'include/*'
      - 'meson.build'
      - 'meson-options.txt'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: mingw-w64-x86_64-cmake mingw-w64-x86_64-meson mingw-w64-x86_64-gcc mingw-w64-x86_64-vapoursynth

    - name: Configure and build
      run: |
        meson setup builddir --buildtype release
        meson compile -C builddir

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: descale-win64
        path: builddir/libdescale.dll
